name: CI for Remote SimpCity

on:
  push:
    branches: [master]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Run Local Developer Tests
      run: |
        pytest --cov -v --junitxml=report.xml
    - if: ${{failure()}}
      name: Create Issue
      token: ${{secrets.GITHUB_TOKEN}}
      assignees: ${{github.actor}}
      labels: workflow-failed
      body: Workflow failed for commit ${{github.sha}} @ ${{github.ref}}
    
     - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.24
      if: always()
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        files: report.xml